import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { renderToStaticMarkup } from "react-dom/server";

import ArticleBody from "../app/components/blog/ArticleBody";
import { PREVIEW_FIXTURE } from "../app/blog/preview-fixture";

/**
 * Renders the parity fixture through the real `ArticleBody` and writes the
 * result where the blog-cms repo can assert against it.
 *
 * The live preview makes the *online* path drift-proof by construction — it is
 * literally this component. The CMS still ships an offline fallback renderer,
 * and this golden file is what keeps that copy honest: regenerate after any
 * change to `ArticleBody`, and the CMS test fails until its copy matches.
 *
 *   npm run golden            # write both copies
 *   BLOG_CMS_DIR=… npm run golden
 */

const HEADER = [
  "<!--",
  "  GENERATED by personal-website: npm run golden",
  "  Source: app/components/blog/ArticleBody.tsx + app/blog/preview-fixture.ts",
  "  Do not edit by hand.",
  "-->",
  "",
].join("\n");

async function exists(target: string): Promise<boolean> {
  try {
    await access(target);

    return true;
  } catch {
    return false;
  }
}

async function main() {
  const markup = renderToStaticMarkup(<ArticleBody content={PREVIEW_FIXTURE} />);
  const contents = `${HEADER}${markup}\n`;

  const local = path.join(process.cwd(), "golden", "article-body.html");
  await mkdir(path.dirname(local), { recursive: true });
  await writeFile(local, contents, "utf8");
  console.log(`wrote ${path.relative(process.cwd(), local)}`);

  const cmsDir =
    process.env.BLOG_CMS_DIR ?? path.resolve(process.cwd(), "..", "blog-cms");

  if (!(await exists(cmsDir))) {
    console.warn(
      `blog-cms not found at ${cmsDir} — skipped its copy. Set BLOG_CMS_DIR to point at it.`,
    );

    return;
  }

  const targetDir = path.join(cmsDir, "tests", "golden");
  await mkdir(targetDir, { recursive: true });

  await writeFile(path.join(targetDir, "article-body.html"), contents, "utf8");
  // The fixture travels with the golden so the CMS never has to keep its own
  // copy of the input — one authored source, two consumers.
  await writeFile(
    path.join(targetDir, "fixture.json"),
    `${JSON.stringify(PREVIEW_FIXTURE, null, 2)}\n`,
    "utf8",
  );

  console.log(`wrote ${path.join(targetDir, "article-body.html")}`);
  console.log(`wrote ${path.join(targetDir, "fixture.json")}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
